import torch
LEARNING_RATE = 0.001
BATCH_SIZE = 32
EPOCHS = 1
NUM_CLASSES = 26
PATCH_SIZE = 4
IMG_SIZE = 28
IN_CHANNELS = 1
NUM_HEADS = 4
HIDDEN_DIMENSION = 128
DROPOUT = 0.1
ADAM_WEIGHT_DECAY = 0.01
ADAM_BETAS = (0.9, 0.999)
ACTIVATION = "gelu"
NUM_ENCODERS = 2
EMBED_DIM = (PATCH_SIZE**2)*IN_CHANNELS 
NUM_PATCHES = (IMG_SIZE//PATCH_SIZE)**2 

device = "cuda" if torch.cuda.is_available() else "cpu"
